### ISSUE TITLE
suggestions + joining forces!

### ISSUE THREAD

**Issue by route1rodent** [thatrs/Pokemon-Red-Unity#1]
hey I know that the issues is not the right place to do this, but I didn't have any other way to contact you.
I just wanted to say hi, and congratulate you for starting this fabulous project. I think that my project NewBark (the Pokemon Gold engine for Unity) can learn something from it :)

I downloaded and tried it, the first thing I noticed is that there are a lot of tilemaps and gameobjects in a single scene and that is very resource intensive. Did you think about separate them in different scenes?

Well if you need something from Newbark you can always take some ideas from it too and you are also welcome to contribute to the project, I am looking for new Unity developers to help a little more to make some more progress ;) 

I use the ["Projects" and "Issues"](https://github.com/route1rodent/newbark/projects) tabs a lot, so I have always documented what's coming next and I don't forget. There you can see what's going on and kind of the roadmap. 

Thanks for starring the project and see you!

**Comment by CelestialAmber** [comment]
Thanks! It makes me happy to see more "recreation" projects (even if just a small part of a game) in Unity. I hope that I can learn from your project as well. 

I was considering splitting the maps into separate scenes, but I didn't know how to specifically manage that, so I just decided to go with my current approach for now. But I'm definitely considering changing it to using separate scenes.
